os:
  - linux

language: cpp
dist: xenial

before_install:
  - sudo add-apt-repository ppa:jonathonf/gcc-7.1 -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-7 g++-7

addons:
  apt:
    packages:
      - libboost-all-dev
      - catch
      - cmake
      - qtbase5-dev
      - libfreeimageplus-dev
      - doxygen
      - cppcheck
      - libclang-6.0-dev
      - clang-tools-6.0
      - clang-format-6.0
      - clang-tidy-6.0
      - liblog4cxx-dev

branches:
  only:
    - master
    - devel

before_script:
  - git clone https://github.com/swarm-robotics/argos3.git && cd argos3
  - mkdir -p build && cd build
  - cmake ../src
  - make -j 4 && make doc && sudo make install
  - cd ../../

script:

  - export CC=gcc-7;
  - export CXX=g++-7;
  - mkdir -p build && cd build
  - cmake .. && make -j 4
  - make format-all
  - make check-all

  # - cmake -DWITH_TESTS=yes ..
  # - make unit_tests -j 4
  # - make test
