os:
  - linux

language: cpp
dist: xenial

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-9 g++-9

addons:
  apt:
    packages:
      - libboost-all-dev
      - catch
      - cmake
      - qtbase5-dev
      - libfreeimageplus-dev
      - doxygen
      - cppcheck
      - libclang-6.0-dev
      - clang-tools-6.0
      - clang-format-6.0
      - clang-tidy-6.0
      - liblog4cxx-dev

branches:
  only:
    - master
    - devel

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DLIBRA_TESTS=yes ..
  - make -j 4
  - make unit-tests
  - make test
